M48
; DRILL file {KiCad (6.0.5-0)} date Monday, June 13, 2022 at 10:41:11 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-13T22:41:11-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0300
%
G90
G05
T1
X6.6Y-4.3
X6.6Y-4.4
X6.6Y-4.6
X6.6Y-4.7
X7.3Y-4.3
X7.3Y-4.4
X7.3Y-4.6
X7.3Y-4.7
T0
M30
