M48
; DRILL file {KiCad (6.0.5-0)} date Tuesday, September 06, 2022 at 03:59:46 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-06T15:59:46-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X63.297Y-50.825
X63.5Y-111.785
X139.7Y-50.8
X139.7Y-111.76
T0
M30
