M48
; DRILL file {KiCad (6.0.5-0)} date Tuesday, August 16, 2022 at 10:30:28 AM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-16T10:30:28-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X63.271Y-50.673
X63.779Y-111.354
X139.7Y-50.8
X139.7Y-111.76
T0
M30
